# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kilian/Dokumente/coding/M4Baker/m4baker-0.1.2a/m4baker/ui/ModifyBookDlg.ui'
#
# Created: Mon Apr 26 02:01:03 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ModifyBookDlg(object):
    def setupUi(self, ModifyBookDlg):
        ModifyBookDlg.setObjectName("ModifyBookDlg")
        ModifyBookDlg.resize(580, 809)
        self.gridLayout_2 = QtGui.QGridLayout(ModifyBookDlg)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtGui.QGroupBox(ModifyBookDlg)
        self.groupBox.setMinimumSize(QtCore.QSize(121, 0))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.upButton = QtGui.QPushButton(self.groupBox)
        self.upButton.setObjectName("upButton")
        self.gridLayout.addWidget(self.upButton, 0, 0, 1, 1)
        self.addButton = QtGui.QPushButton(self.groupBox)
        self.addButton.setObjectName("addButton")
        self.gridLayout.addWidget(self.addButton, 0, 2, 1, 1)
        self.sortFilenameButton = QtGui.QPushButton(self.groupBox)
        self.sortFilenameButton.setObjectName("sortFilenameButton")
        self.gridLayout.addWidget(self.sortFilenameButton, 0, 3, 1, 1)
        self.downButton = QtGui.QPushButton(self.groupBox)
        self.downButton.setObjectName("downButton")
        self.gridLayout.addWidget(self.downButton, 1, 0, 1, 1)
        self.removeButton = QtGui.QPushButton(self.groupBox)
        self.removeButton.setObjectName("removeButton")
        self.gridLayout.addWidget(self.removeButton, 1, 2, 1, 1)
        self.sortTrackNumberButton = QtGui.QPushButton(self.groupBox)
        self.sortTrackNumberButton.setObjectName("sortTrackNumberButton")
        self.gridLayout.addWidget(self.sortTrackNumberButton, 1, 3, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 2)
        self.tableWidget = QtGui.QTableWidget(ModifyBookDlg)
        self.tableWidget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget.setItem(0, 3, item)
        self.gridLayout_2.addWidget(self.tableWidget, 1, 0, 1, 2)
        self.groupBox_3 = QtGui.QGroupBox(ModifyBookDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.coverLabel = QtGui.QLabel(self.groupBox_3)
        self.coverLabel.setMinimumSize(QtCore.QSize(128, 128))
        self.coverLabel.setMaximumSize(QtCore.QSize(128, 128))
        self.coverLabel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.coverLabel.setFrameShadow(QtGui.QFrame.Sunken)
        self.coverLabel.setText("")
        self.coverLabel.setObjectName("coverLabel")
        self.verticalLayout_2.addWidget(self.coverLabel)
        self.coverButton = QtGui.QPushButton(self.groupBox_3)
        self.coverButton.setObjectName("coverButton")
        self.verticalLayout_2.addWidget(self.coverButton)
        self.gridLayout_2.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(ModifyBookDlg)
        self.groupBox_2.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.authorEdit = QtGui.QLineEdit(self.groupBox_2)
        self.authorEdit.setText("")
        self.authorEdit.setObjectName("authorEdit")
        self.gridLayout_3.addWidget(self.authorEdit, 0, 1, 1, 2)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.titleEdit = QtGui.QLineEdit(self.groupBox_2)
        self.titleEdit.setText("")
        self.titleEdit.setObjectName("titleEdit")
        self.gridLayout_3.addWidget(self.titleEdit, 1, 1, 1, 2)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.yearEdit = QtGui.QLineEdit(self.groupBox_2)
        self.yearEdit.setInputMask("")
        self.yearEdit.setMaxLength(4)
        self.yearEdit.setObjectName("yearEdit")
        self.gridLayout_3.addWidget(self.yearEdit, 2, 1, 1, 2)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.outfileButton = QtGui.QToolButton(self.groupBox_2)
        self.outfileButton.setObjectName("outfileButton")
        self.gridLayout_3.addWidget(self.outfileButton, 3, 1, 1, 1)
        self.outfileEdit = QtGui.QLineEdit(self.groupBox_2)
        self.outfileEdit.setAcceptDrops(False)
        self.outfileEdit.setReadOnly(True)
        self.outfileEdit.setObjectName("outfileEdit")
        self.gridLayout_3.addWidget(self.outfileEdit, 3, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtGui.QLabel(ModifyBookDlg)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.faacEdit = QtGui.QLineEdit(ModifyBookDlg)
        self.faacEdit.setObjectName("faacEdit")
        self.horizontalLayout_2.addWidget(self.faacEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 0, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.splitCheckBox = QtGui.QCheckBox(ModifyBookDlg)
        self.splitCheckBox.setChecked(False)
        self.splitCheckBox.setTristate(False)
        self.splitCheckBox.setObjectName("splitCheckBox")
        self.horizontalLayout.addWidget(self.splitCheckBox)
        self.splitTimeEdit = QtGui.QTimeEdit(ModifyBookDlg)
        self.splitTimeEdit.setEnabled(False)
        self.splitTimeEdit.setObjectName("splitTimeEdit")
        self.horizontalLayout.addWidget(self.splitTimeEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout, 4, 0, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(ModifyBookDlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 5, 0, 1, 2)
        self.label.setBuddy(self.authorEdit)
        self.label_2.setBuddy(self.titleEdit)
        self.label_3.setBuddy(self.yearEdit)
        self.label_4.setBuddy(self.outfileEdit)
        self.label_5.setBuddy(self.faacEdit)

        self.retranslateUi(ModifyBookDlg)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ModifyBookDlg.reject)
        QtCore.QObject.connect(self.splitCheckBox, QtCore.SIGNAL("toggled(bool)"), self.splitTimeEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ModifyBookDlg)

    def retranslateUi(self, ModifyBookDlg):
        ModifyBookDlg.setWindowTitle(QtGui.QApplication.translate("ModifyBookDlg", "Modify audiobook", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ModifyBookDlg", "Manage Chapters", None, QtGui.QApplication.UnicodeUTF8))
        self.upButton.setText(QtGui.QApplication.translate("ModifyBookDlg", "up", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setText(QtGui.QApplication.translate("ModifyBookDlg", "add", None, QtGui.QApplication.UnicodeUTF8))
        self.sortFilenameButton.setText(QtGui.QApplication.translate("ModifyBookDlg", "sort by Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.downButton.setText(QtGui.QApplication.translate("ModifyBookDlg", "down", None, QtGui.QApplication.UnicodeUTF8))
        self.removeButton.setText(QtGui.QApplication.translate("ModifyBookDlg", "remove", None, QtGui.QApplication.UnicodeUTF8))
        self.sortTrackNumberButton.setText(QtGui.QApplication.translate("ModifyBookDlg", "sort by Track number", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("ModifyBookDlg", "track number", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("ModifyBookDlg", "title", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("ModifyBookDlg", "duration", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("ModifyBookDlg", "start time", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("ModifyBookDlg", "filename", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_3.setTitle(QtGui.QApplication.translate("ModifyBookDlg", "Cover", None, QtGui.QApplication.UnicodeUTF8))
        self.coverButton.setText(QtGui.QApplication.translate("ModifyBookDlg", "change", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("ModifyBookDlg", "Metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ModifyBookDlg", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ModifyBookDlg", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ModifyBookDlg", "Year", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ModifyBookDlg", "Output file", None, QtGui.QApplication.UnicodeUTF8))
        self.outfileButton.setText(QtGui.QApplication.translate("ModifyBookDlg", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ModifyBookDlg", "faac command line", None, QtGui.QApplication.UnicodeUTF8))
        self.splitCheckBox.setText(QtGui.QApplication.translate("ModifyBookDlg", "autosplit every  hh:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.splitTimeEdit.setDisplayFormat(QtGui.QApplication.translate("ModifyBookDlg", "HH:mm:ss", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ModifyBookDlg = QtGui.QDialog()
    ui = Ui_ModifyBookDlg()
    ui.setupUi(ModifyBookDlg)
    ModifyBookDlg.show()
    sys.exit(app.exec_())

